"""
SmartCityAI - Schemas Package
Exports API Pydantic schemas.
"""

from backend.schemas.api_schemas import (
    PaginationParams,
    PaginatedResponse,
    ErrorResponse,
    TrafficRecordBase,
    TrafficRecordCreate,
    TrafficRecordResponse,
    TrafficForecastRequest,
    TrafficForecastResponse,
    AccidentRecordBase,
    AccidentRecordCreate,
    AccidentRecordResponse,
    AccidentRiskScoreRequest,
    AccidentRiskScoreResponse,
    AirQualityRecordBase,
    AirQualityRecordCreate,
    AirQualityRecordResponse,
    AQIForecastRequest,
    AQIForecastResponse,
    AnomalyRecordResponse,
    AnomalyDetectionRequest,
    AnomalyDetectionResponse,
    GeoJSONGeometry,
    GeoJSONFeature,
    GeoJSONFeatureCollection,
    InsightQueryRequest,
    CityHealthSummaryResponse,
    ComponentHealth,
    HealthCheckResponse,
)

__all__ = [
    "PaginationParams",
    "PaginatedResponse",
    "ErrorResponse",
    "TrafficRecordBase",
    "TrafficRecordCreate",
    "TrafficRecordResponse",
    "TrafficForecastRequest",
    "TrafficForecastResponse",
    "AccidentRecordBase",
    "AccidentRecordCreate",
    "AccidentRecordResponse",
    "AccidentRiskScoreRequest",
    "AccidentRiskScoreResponse",
    "AirQualityRecordBase",
    "AirQualityRecordCreate",
    "AirQualityRecordResponse",
    "AQIForecastRequest",
    "AQIForecastResponse",
    "AnomalyRecordResponse",
    "AnomalyDetectionRequest",
    "AnomalyDetectionResponse",
    "GeoJSONGeometry",
    "GeoJSONFeature",
    "GeoJSONFeatureCollection",
    "InsightQueryRequest",
    "CityHealthSummaryResponse",
    "ComponentHealth",
    "HealthCheckResponse",
]
